### ISSUE TITLE
PyQT5 from package python3-pyqt5 instead from requirements file

### ISSUE THREAD

**Issue by ghmon** [g4ixt/QtTinySA#44]
When installing requirements pyqt5 is installed. This works for QtTinySA, but e.g. plugin loading for qgis is broken cause of an unresolved symbol.

Solution was: uninstalling pyqt5 with pip, installing with apt python3-pyqt5. Works also for QtTinySA.

python 3.10.12. Ubuntu 22.04 LTS. Did not use a venv.

**Comment by g4ixt** [comment]
In the Wiki 'dependencies' page I recommend installing from the repository if you can.  I try not to use PIP, except with my 'venv' that I use to build the exectutables.

On the Raspberry Pi OS12 'bookworm' the use of PIP has been blocked, which caused me some problems running the python programme there - I had to put the QtTSAprefs.db file in the folder because I was unable to find a way to update 'platformdirs' and got the same errors that you did.

**Comment by ghmon** [comment]
Thanks!
